-- Вставляем профили фрилансеров с реалистичными данными
INSERT INTO t_p96553691_freelance_platform_c.freelancers (user_id, bio, hourly_rate, avatar_url, skills, rating, total_reviews, completed_projects)
SELECT u.id, d.bio, d.hourly_rate, d.f_avatar_url, d.skills::text[], d.rating, d.total_reviews, d.completed_projects
FROM t_p96553691_freelance_platform_c.users u
JOIN (VALUES
  ('alexei_smirnov',    'Fullstack-разработчик с 8 летним опытом. Специализируюсь на React и Node.js.',                         3500, 'https://api.dicebear.com/7.x/avataaars/svg?seed=alexei',       '{React,Node.js,TypeScript,PostgreSQL}',         4.95, 87,  124),
  ('maria_ivanova',     'UI/UX дизайнер. Создаю продукты, которыми приятно пользоваться. Figma, Sketch, прототипирование.',     2800, 'https://api.dicebear.com/7.x/avataaars/svg?seed=maria',         '{Figma,UI/UX,Sketch,Prototyping}',              4.90, 73,  98),
  ('dmitry_petrov',     'Python-разработчик и дата-инженер. Опыт в ML, анализе данных и построении ETL-пайплайнов.',            4200, 'https://api.dicebear.com/7.x/avataaars/svg?seed=dmitry',        '{Python,ML,Django,PostgreSQL,Docker}',          4.88, 61,  89),
  ('elena_kozlova',     'Копирайтер и контент-стратег. Пишу тексты, которые продают: лендинги, email-рассылки, статьи.',       1200, 'https://api.dicebear.com/7.x/avataaars/svg?seed=elena',         '{Копирайтинг,SEO,Email,Блог}',                  4.93, 112, 201),
  ('sergey_novikov',    'Мобильный разработчик iOS и Android. Более 40 приложений в App Store и Google Play.',                   5000, 'https://api.dicebear.com/7.x/avataaars/svg?seed=sergey',        '{Swift,Kotlin,React Native,Flutter}',           4.85, 54,  67),
  ('olga_morozova',     'Специалист по таргетированной и контекстной рекламе. Работала с бюджетами до 5 млн рублей.',           2000, 'https://api.dicebear.com/7.x/avataaars/svg?seed=olga',          '{Таргет,Google Ads,Яндекс.Директ,SMM}',        4.78, 45,  78),
  ('andrei_volkov',     'DevOps-инженер. Настройка CI/CD, Kubernetes, мониторинг. Помогаю командам выпускать продукты быстрее.',4800, 'https://api.dicebear.com/7.x/avataaars/svg?seed=andrei',        '{DevOps,Kubernetes,Docker,CI/CD,AWS}',          4.92, 38,  52),
  ('natasha_sokolova',  'Видеомонтажёр и моушн-дизайнер. Ролики для YouTube, Instagram, рекламные видео, анимация.',           1800, 'https://api.dicebear.com/7.x/avataaars/svg?seed=natasha',        '{Видеомонтаж,After Effects,Premiere,Анимация}', 4.87, 95,  143),
  ('ivan_popov',        'Backend-разработчик на Go и Java. Высоконагруженные системы, микросервисы, API.',                       4500, 'https://api.dicebear.com/7.x/avataaars/svg?seed=ivan',          '{Go,Java,Microservices,Kafka,Redis}',           4.83, 42,  61),
  ('tatyana_lebedeva',  'SMM-менеджер. Веду аккаунты в Instagram, ВКонтакте, Telegram. Рост подписчиков и вовлечённости.',     1500, 'https://api.dicebear.com/7.x/avataaars/svg?seed=tatyana',        '{SMM,Instagram,ВКонтакте,Telegram,Контент}',   4.76, 67,  89),
  ('mikhail_kozlov',    '1С разработчик и консультант. Автоматизация бизнес-процессов, интеграции, написание отчётов.',         3200, 'https://api.dicebear.com/7.x/avataaars/svg?seed=mikhail',        '{1С,ERP,Бухгалтерия,Автоматизация}',           4.80, 33,  47),
  ('anna_novikova',     'Графический дизайнер. Логотипы, фирменный стиль, брендинг, полиграфия. Портфолио 200+ проектов.',     1600, 'https://api.dicebear.com/7.x/avataaars/svg?seed=anna',           '{Дизайн,Логотипы,Брендинг,Illustrator}',       4.91, 134, 218),
  ('pavel_morozov',     'PHP-разработчик, эксперт по WordPress и Bitrix. Разработка сайтов под ключ, интеграции с CRM.',       2500, 'https://api.dicebear.com/7.x/avataaars/svg?seed=pavel',          '{PHP,WordPress,Bitrix,MySQL}',                  4.72, 88,  131),
  ('yuliya_volkova',    'Переводчик с английского, немецкого и французского. Технические и маркетинговые тексты.',              900,  'https://api.dicebear.com/7.x/avataaars/svg?seed=yuliya',         '{Перевод,Английский,Немецкий,Французский}',    4.96, 149, 267),
  ('nikita_sokolov',    'Аналитик данных. SQL, Python, Power BI, Tableau. Помогаю принимать решения на основе данных.',        3000, 'https://api.dicebear.com/7.x/avataaars/svg?seed=nikita',         '{SQL,Python,Power BI,Tableau,Excel}',           4.84, 56,  74),
  ('katerina_popova',   'HR-специалист и рекрутер. Подбор IT-специалистов, составление вакансий, проведение интервью.',        1400, 'https://api.dicebear.com/7.x/avataaars/svg?seed=katerina',       '{HR,Рекрутинг,IT-рекрутинг,Headhunting}',      4.79, 41,  58),
  ('roman_lebedev',     'SEO-специалист. Вывод сайтов в топ Яндекса и Google. Технический SEO, линкбилдинг.',                  2200, 'https://api.dicebear.com/7.x/avataaars/svg?seed=roman',          '{SEO,Яндекс,Google,Линкбилдинг,Аналитика}',   4.77, 79,  103),
  ('oksana_kozlova',    'Бухгалтер и налоговый консультант. УСН, ОСНО, ИП и ООО. Подготовка отчётности.',                     1800, 'https://api.dicebear.com/7.x/avataaars/svg?seed=oksana',         '{Бухгалтерия,Налоги,1С,Отчётность}',           4.94, 103, 187),
  ('artem_novikov',     'Тестировщик QA. Ручное и автоматизированное тестирование. Selenium, Cypress, Appium.',                2600, 'https://api.dicebear.com/7.x/avataaars/svg?seed=artem',          '{QA,Selenium,Cypress,Тестирование,Appium}',    4.81, 47,  65),
  ('svetlana_morozova', 'Иллюстратор и художник. Цифровые иллюстрации, персонажи, комиксы, детские книги.',                   1700, 'https://api.dicebear.com/7.x/avataaars/svg?seed=svetlana',       '{Иллюстрация,Procreate,Photoshop,Персонажи}',  4.89, 76,  112),
  ('maxim_volkov',      'Специалист по кибербезопасности. Пентест, аудит безопасности, настройка защиты серверов.',            5500, 'https://api.dicebear.com/7.x/avataaars/svg?seed=maxim',          '{Кибербезопасность,Пентест,Linux,Сети}',        4.97, 29,  38),
  ('viktoriya_sokolova','Продюсер и проджект-менеджер. Управление командами, agile, запуск продуктов от идеи до релиза.',      2400, 'https://api.dicebear.com/7.x/avataaars/svg?seed=viktoriya',      '{PM,Agile,Scrum,Продуктовый менеджмент}',      4.86, 52,  71),
  ('konstantin_popov',  'Разработчик игр на Unity. 2D и 3D игры, мобильные игры, VR. Опыт публикации в Steam.',               3800, 'https://api.dicebear.com/7.x/avataaars/svg?seed=konstantin',     '{Unity,C#,GameDev,VR,Mobile}',                  4.82, 35,  44),
  ('darya_lebedeva',    'Психолог и бизнес-коуч. Консультации для предпринимателей, командный коучинг, личная эффективность.',2000, 'https://api.dicebear.com/7.x/avataaars/svg?seed=darya',          '{Коучинг,Психология,Тренинги,HR}',              4.98, 91,  156),
  ('vladislav_smirnov', 'Эксперт по автоматизации маркетинга. CRM-интеграции, email-воронки, чат-боты для бизнеса.',          3100, 'https://api.dicebear.com/7.x/avataaars/svg?seed=vladislav',      '{CRM,Email-маркетинг,Чат-боты,Автоматизация}', 4.75, 63,  84),
  ('alina_ivanova',     'Фотограф и ретушёр. Предметная, портретная и репортажная фотография. Lightroom и Photoshop.',        1300, 'https://api.dicebear.com/7.x/avataaars/svg?seed=alina',          '{Фотография,Ретушь,Lightroom,Photoshop}',       4.88, 108, 172),
  ('georgy_petrov',     'Юрист и правовой консультант. Договорная работа, регистрация бизнеса, интеллектуальная собственность.',2800,'https://api.dicebear.com/7.x/avataaars/svg?seed=georgy',        '{Юриспруденция,Договоры,Право,IP}',             4.93, 77,  119),
  ('polina_kozlova',    'Специалист по контекстной рекламе. Яндекс.Директ, Google Ads. Снижение стоимости лида.',             2100, 'https://api.dicebear.com/7.x/avataaars/svg?seed=polina',         '{Яндекс.Директ,Google Ads,PPC,ROI}',            4.80, 58,  79),
  ('denis_novikov',     '3D-моделлер и визуализатор. Архитектурная визуализация, продуктовые рендеры, анимация.',             2700, 'https://api.dicebear.com/7.x/avataaars/svg?seed=denis',          '{3D Max,Blender,3D визуализация,Cinema 4D}',    4.85, 44,  60),
  ('anastasiya_morozova','Специалист по финансовому планированию. Бюджетирование, инвестиционный анализ, финмодели.',          3300, 'https://api.dicebear.com/7.x/avataaars/svg?seed=anastasiya',     '{Финансы,Excel,Бюджетирование,Инвестиции}',    4.91, 66,  94)
) AS d(username, bio, hourly_rate, f_avatar_url, skills, rating, total_reviews, completed_projects)
ON u.username = d.username;
