-- Вставляем 30 пользователей-фрилансеров
INSERT INTO t_p96553691_freelance_platform_c.users (google_id, email, name, username, password_hash)
VALUES
('freelancer_001', 'alexei.smirnov@freelance.ru', 'Алексей Смирнов', 'alexei_smirnov', 'dummy'),
('freelancer_002', 'maria.ivanova@freelance.ru', 'Мария Иванова', 'maria_ivanova', 'dummy'),
('freelancer_003', 'dmitry.petrov@freelance.ru', 'Дмитрий Петров', 'dmitry_petrov', 'dummy'),
('freelancer_004', 'elena.kozlova@freelance.ru', 'Елена Козлова', 'elena_kozlova', 'dummy'),
('freelancer_005', 'sergey.novikov@freelance.ru', 'Сергей Новиков', 'sergey_novikov', 'dummy'),
('freelancer_006', 'olga.morozova@freelance.ru', 'Ольга Морозова', 'olga_morozova', 'dummy'),
('freelancer_007', 'andrei.volkov@freelance.ru', 'Андрей Волков', 'andrei_volkov', 'dummy'),
('freelancer_008', 'natasha.sokolova@freelance.ru', 'Наташа Соколова', 'natasha_sokolova', 'dummy'),
('freelancer_009', 'ivan.popov@freelance.ru', 'Иван Попов', 'ivan_popov', 'dummy'),
('freelancer_010', 'tatyana.lebedeva@freelance.ru', 'Татьяна Лебедева', 'tatyana_lebedeva', 'dummy'),
('freelancer_011', 'mikhail.kozlov@freelance.ru', 'Михаил Козлов', 'mikhail_kozlov', 'dummy'),
('freelancer_012', 'anna.novikova@freelance.ru', 'Анна Новикова', 'anna_novikova', 'dummy'),
('freelancer_013', 'pavel.morozov@freelance.ru', 'Павел Морозов', 'pavel_morozov', 'dummy'),
('freelancer_014', 'yuliya.volkova@freelance.ru', 'Юлия Волкова', 'yuliya_volkova', 'dummy'),
('freelancer_015', 'nikita.sokolov@freelance.ru', 'Никита Соколов', 'nikita_sokolov', 'dummy'),
('freelancer_016', 'katerina.popova@freelance.ru', 'Катерина Попова', 'katerina_popova', 'dummy'),
('freelancer_017', 'roman.lebedev@freelance.ru', 'Роман Лебедев', 'roman_lebedev', 'dummy'),
('freelancer_018', 'oksana.kozlova2@freelance.ru', 'Оксана Козлова', 'oksana_kozlova', 'dummy'),
('freelancer_019', 'artem.novikov2@freelance.ru', 'Артём Новиков', 'artem_novikov', 'dummy'),
('freelancer_020', 'svetlana.morozova2@freelance.ru', 'Светлана Морозова', 'svetlana_morozova', 'dummy'),
('freelancer_021', 'maxim.volkov2@freelance.ru', 'Максим Волков', 'maxim_volkov', 'dummy'),
('freelancer_022', 'viktoriya.sokolova2@freelance.ru', 'Виктория Соколова', 'viktoriya_sokolova', 'dummy'),
('freelancer_023', 'konstantin.popov2@freelance.ru', 'Константин Попов', 'konstantin_popov', 'dummy'),
('freelancer_024', 'darya.lebedeva2@freelance.ru', 'Дарья Лебедева', 'darya_lebedeva', 'dummy'),
('freelancer_025', 'vladislav.smirnov2@freelance.ru', 'Владислав Смирнов', 'vladislav_smirnov', 'dummy'),
('freelancer_026', 'alina.ivanova2@freelance.ru', 'Алина Иванова', 'alina_ivanova', 'dummy'),
('freelancer_027', 'georgy.petrov2@freelance.ru', 'Георгий Петров', 'georgy_petrov', 'dummy'),
('freelancer_028', 'polina.kozlova3@freelance.ru', 'Полина Козлова', 'polina_kozlova', 'dummy'),
('freelancer_029', 'denis.novikov3@freelance.ru', 'Денис Новиков', 'denis_novikov', 'dummy'),
('freelancer_030', 'anastasiya.morozova3@freelance.ru', 'Анастасия Морозова', 'anastasiya_morozova', 'dummy');
