INSERT INTO t_p96553691_freelance_platform_c.freelancers (user_id, bio, hourly_rate, avatar_url, skills, rating, total_reviews, completed_projects)
SELECT u.id, d.bio, d.hr, d.av, d.sk::text[], d.rat, d.rev, d.cp
FROM t_p96553691_freelance_platform_c.users u
JOIN (VALUES
('boris_shubin','Fullstack Laravel + Vue.js. Разрабатываю SaaS-продукты и корпоративные порталы.',3200,'https://api.dicebear.com/7.x/avataaars/svg?seed=boris','{Laravel,Vue.js,PHP,MySQL,Docker}',4.79,58,83),
('kseniya_belova','Иллюстратор. Персонажи, обложки книг, детские иллюстрации, паттерны.',1900,'https://api.dicebear.com/7.x/avataaars/svg?seed=kseniya','{Иллюстрация,Procreate,Паттерны,Персонажи}',4.87,71,109),
('timur_gusev','iOS-разработчик Swift. Пишу нативные приложения с фокусом на производительность.',4600,'https://api.dicebear.com/7.x/avataaars/svg?seed=timur','{Swift,SwiftUI,Xcode,iOS,CoreData}',4.83,44,58),
('vera_soboleva','Копирайтер для e-commerce. Карточки товаров, лендинги, рассылки.',1100,'https://api.dicebear.com/7.x/avataaars/svg?seed=vera','{Копирайтинг,E-commerce,SEO,Рассылки}',4.91,96,172),
('ilya_fedoseev','Data Engineer. Строю ETL-пайплайны, работаю с Spark, Kafka, Airflow.',5200,'https://api.dicebear.com/7.x/avataaars/svg?seed=ilya','{Spark,Kafka,Airflow,Python,BigData}',4.85,31,43),
('marina_chernova','SMM для fashion и beauty. Рост охватов, Reels, коллаборации с блогерами.',1700,'https://api.dicebear.com/7.x/avataaars/svg?seed=marina_c','{SMM,Reels,Fashion,Beauty,TikTok}',4.76,67,91),
('oleg_nikitin','Backend Go-разработчик. Микросервисы, высоконагруженные API, gRPC.',4900,'https://api.dicebear.com/7.x/avataaars/svg?seed=oleg','{Go,gRPC,Microservices,Kubernetes,Redis}',4.88,39,52),
('sofia_voronova','UX-исследователь. Проектирую пользовательские интервью, CJM, юзабилити-тесты.',3000,'https://api.dicebear.com/7.x/avataaars/svg?seed=sofia','{UX Research,CJM,Figma,Usability,Интервью}',4.92,55,74),
('ruslan_zimin','Разработчик Telegram Mini Apps и ботов. aiogram, React, TWA.',2800,'https://api.dicebear.com/7.x/avataaars/svg?seed=ruslan','{Telegram,aiogram,React,TWA,Python}',4.81,48,65),
('lyudmila_efimova','Бухгалтер-аутсорс. Ведение ИП и ООО, сдача отчётности, оптимизация налогов.',1600,'https://api.dicebear.com/7.x/avataaars/svg?seed=lyudmila','{Бухгалтерия,1С,Налоги,УСН,ОСНО}',4.94,88,154),
('alexandr_sidorov','Android-разработчик. Kotlin, Jetpack Compose, публикация в Google Play.',4300,'https://api.dicebear.com/7.x/avataaars/svg?seed=alexandr','{Kotlin,Jetpack Compose,Android,Firebase}',4.80,41,55),
('natalya_bogdanova','Переводчик технических и юридических текстов. EN/DE/FR ↔ RU.',950,'https://api.dicebear.com/7.x/avataaars/svg?seed=natalya','{Перевод,Английский,Немецкий,Юридический}',4.96,121,224),
('vadim_kurilenko','DevOps. Настройка GitLab CI, Docker, Kubernetes, мониторинг Grafana.',4700,'https://api.dicebear.com/7.x/avataaars/svg?seed=vadim_k','{GitLab CI,Docker,Kubernetes,Grafana,Terraform}',4.89,36,49),
('elena_filatova','Графический дизайнер. Упаковка, этикетки, POS-материалы, полиграфия.',1800,'https://api.dicebear.com/7.x/avataaars/svg?seed=elena_f','{Дизайн,Упаковка,Illustrator,Полиграфия}',4.84,74,112),
('alexey_borisov','React Native разработчик. Кросс-платформенные приложения iOS+Android.',3800,'https://api.dicebear.com/7.x/avataaars/svg?seed=alexey_b','{React Native,JavaScript,iOS,Android,Expo}',4.77,52,69),
('irina_sharapova','Контент-маркетолог. Стратегия, редполитика, управление командой авторов.',2600,'https://api.dicebear.com/7.x/avataaars/svg?seed=irina_sh','{Контент,Редполитика,Стратегия,Блог,SEO}',4.86,63,87),
('grigoriy_naumov','Специалист по автоматизации 1С. Конфигурации, интеграции, отчёты.',3400,'https://api.dicebear.com/7.x/avataaars/svg?seed=grigoriy','{1С,Конфигурации,Интеграции,Отчёты}',4.78,45,61),
('polina_suvorova','Видеограф и фотограф. Съёмка мероприятий, продукта, интерьеров.',2200,'https://api.dicebear.com/7.x/avataaars/svg?seed=polina_s','{Фотография,Видеосъёмка,Premiere,Lightroom}',4.90,82,130),
('kirill_morozov','Разработчик игр Unity. Мобильные казуальные игры, монетизация, публикация.',3700,'https://api.dicebear.com/7.x/avataaars/svg?seed=kirill','{Unity,C#,Mobile Games,GameDev,Monetization}',4.82,37,48),
('diana_stepanova','HR и рекрутер. Закрываю IT и digital-вакансии, онбординг, HR-бренд.',1500,'https://api.dicebear.com/7.x/avataaars/svg?seed=diana','{HR,Рекрутинг,IT,Онбординг,HR-бренд}',4.75,54,72),
('evgeny_shilov','Backend Python + Django. REST API, интеграции, высоконагруженные системы.',4000,'https://api.dicebear.com/7.x/avataaars/svg?seed=evgeny','{Python,Django,REST API,PostgreSQL,Redis}',4.83,46,63),
('tatyana_abramova','Флорист и декоратор. Декор мероприятий, оформление фотозон, мастер-классы.',1200,'https://api.dicebear.com/7.x/avataaars/svg?seed=tatyana_a','{Флористика,Декор,Фотозоны,Мастер-классы}',4.97,103,189),
('ivan_savin','Специалист по кибербезопасности. Аудит, пентест, настройка WAF.',5300,'https://api.dicebear.com/7.x/avataaars/svg?seed=ivan_s','{Кибербезопасность,Пентест,WAF,Linux,SIEM}',4.95,28,36),
('olga_koroleva','Дизайнер интерьеров. 3D-визуализация, рабочая документация, авторский надзор.',3100,'https://api.dicebear.com/7.x/avataaars/svg?seed=olga_k','{Интерьеры,3ds Max,AutoCAD,SketchUp,Визуализация}',4.88,66,95),
('nikolay_smirnov','Fullstack Next.js + Node.js. Разработка SaaS с нуля, performance-оптимизация.',4100,'https://api.dicebear.com/7.x/avataaars/svg?seed=nikolay','{Next.js,Node.js,TypeScript,PostgreSQL,AWS}',4.84,50,68),
('yulia_antonova','Психолог. Онлайн-консультации, тренинги, разработка обучающих программ.',1800,'https://api.dicebear.com/7.x/avataaars/svg?seed=yulia_a','{Психология,Коучинг,Тренинги,CBT}',4.98,91,167),
('dmitriy_baranov','Архитектор облачных решений AWS/GCP. Проектирование инфраструктуры, FinOps.',5800,'https://api.dicebear.com/7.x/avataaars/svg?seed=dmitriy_b','{AWS,GCP,Terraform,FinOps,Архитектура}',4.91,32,42),
('anna_kazakova','Копирайтер для B2B. Белые книги, кейсы, питч-деки, коммерческие предложения.',1500,'https://api.dicebear.com/7.x/avataaars/svg?seed=anna_k','{B2B,Копирайтинг,Кейсы,Презентации}',4.87,77,118),
('maxim_titov','3D-аниматор. Продуктовые анимации, рекламные ролики, архитектурные облёты.',3500,'https://api.dicebear.com/7.x/avataaars/svg?seed=maxim_t','{Cinema 4D,Blender,3D Animation,After Effects}',4.85,43,58),
('svetlana_egorova','Юрист. Корпоративное право, M&A, структурирование сделок.',3200,'https://api.dicebear.com/7.x/avataaars/svg?seed=svetlana_e','{Корпоративное право,M&A,Договоры,Due Diligence}',4.93,69,105),
('roman_kovalev','Специалист по автоматизации маркетинга. HubSpot, Unisender, Bitrix24.',2900,'https://api.dicebear.com/7.x/avataaars/svg?seed=roman_k','{HubSpot,CRM,Email,Автоматизация,Bitrix24}',4.78,58,79),
('alena_belousova','Моушн-дизайнер. Анимированные логотипы, рекламные ролики, UI-анимации.',2700,'https://api.dicebear.com/7.x/avataaars/svg?seed=alena','{After Effects,Motion Design,UI Animation}',4.89,74,109),
('artem_sorokin','Специалист по маркетплейсам. Полный цикл вывода товара на WB и Ozon.',2400,'https://api.dicebear.com/7.x/avataaars/svg?seed=artem_s','{Wildberries,Ozon,Маркетплейсы,Реклама,SEO}',4.82,86,134),
('kristina_kozlova2','Нутрициолог и фитнес-тренер. Персональные планы питания и тренировок.',1300,'https://api.dicebear.com/7.x/avataaars/svg?seed=kristina','{Нутрициология,Фитнес,ЗОЖ,Консультации}',4.94,112,198),
('igor_frolov','Системный администратор. Настройка Windows Server, Active Directory, VMware.',3600,'https://api.dicebear.com/7.x/avataaars/svg?seed=igor','{Windows Server,Active Directory,VMware,Сети}',4.79,38,52),
('viktoriya_zubova','Ивент-менеджер. Организация корпоративов, конференций, онлайн-мероприятий.',2100,'https://api.dicebear.com/7.x/avataaars/svg?seed=viktoriya_z','{Ивент,Корпоративы,Конференции,Онлайн}',4.86,57,83),
('andrei_kuznetsov','Embedded-разработчик. C/C++ для STM32, ESP32, Raspberry Pi, IoT-решения.',4400,'https://api.dicebear.com/7.x/avataaars/svg?seed=andrei_k','{C/C++,STM32,ESP32,IoT,Embedded}',4.80,29,39),
('lilia_medvedeva','Финансовый аналитик. Финмодели, DCF, инвестиционные меморандумы для стартапов.',3300,'https://api.dicebear.com/7.x/avataaars/svg?seed=lilia','{Финансы,DCF,Excel,Финмодели,Инвестиции}',4.90,61,89),
('stanislav_popov','Разработчик на Rust. Системное ПО, WebAssembly, высокопроизводительные сервисы.',5100,'https://api.dicebear.com/7.x/avataaars/svg?seed=stanislav','{Rust,WebAssembly,Systems,Performance}',4.88,22,29),
('vera_mikhailova','Продюсер подкастов. Монтаж, продвижение, поиск спонсоров, обложки.',1900,'https://api.dicebear.com/7.x/avataaars/svg?seed=vera_m','{Подкасты,Монтаж,Продвижение,Аудио}',4.83,47,68)
) AS d(username, bio, hr, av, sk, rat, rev, cp)
ON u.username = d.username;
